### ISSUE TITLE
Not able to install the package 

### ISSUE THREAD

**Issue by nitinkumar758** [trondr/sdpeval#5]
Attempting to gather dependency information for package 'sdpeval.1.0.19114.2' with respect to project 'dddemo', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 1.39 sec
Attempting to resolve dependencies for package 'sdpeval.1.0.19114.2' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'sdpeval.1.0.19114.2'
Resolved actions to install package 'sdpeval.1.0.19114.2'
Retrieving package 'Common.Logging 3.4.1' from 'nuget.org'.
Retrieving package 'Common.Logging.Core 3.4.1' from 'nuget.org'.
Retrieving package 'FSharp.Core 4.6.2' from 'nuget.org'.
Retrieving package 'Microsoft.CSharp 4.5.0' from 'nuget.org'.
Retrieving package 'sdpeval 1.0.19114.2' from 'nuget.org'.
Retrieving package 'System.ValueTuple 4.5.0' from 'nuget.org'.
Adding package 'FSharp.Core.4.6.2' to folder 'C:\Users\Admin\source\repos\dddemo\packages'
Added package 'FSharp.Core.4.6.2' to folder 'C:\Users\Admin\source\repos\dddemo\packages'
Added package 'FSharp.Core.4.6.2' to 'packages.config'
Successfully installed 'FSharp.Core 4.6.2' to dddemo
Adding package 'Microsoft.CSharp.4.5.0' to folder 'C:\Users\Admin\source\repos\dddemo\packages'
Added package 'Microsoft.CSharp.4.5.0' to folder 'C:\Users\Admin\source\repos\dddemo\packages'
Added package 'Microsoft.CSharp.4.5.0' to 'packages.config'
Successfully installed 'Microsoft.CSharp 4.5.0' to dddemo
Adding package 'Common.Logging.Core.3.4.1' to folder 'C:\Users\Admin\source\repos\dddemo\packages'
Added package 'Common.Logging.Core.3.4.1' to folder 'C:\Users\Admin\source\repos\dddemo\packages'
Added package 'Common.Logging.Core.3.4.1' to 'packages.config'
Successfully installed 'Common.Logging.Core 3.4.1' to dddemo
Adding package 'Common.Logging.3.4.1' to folder 'C:\Users\Admin\source\repos\dddemo\packages'
Added package 'Common.Logging.3.4.1' to folder 'C:\Users\Admin\source\repos\dddemo\packages'
Added package 'Common.Logging.3.4.1' to 'packages.config'
Successfully installed 'Common.Logging 3.4.1' to dddemo
Adding package 'System.ValueTuple.4.5.0' to folder 'C:\Users\Admin\source\repos\dddemo\packages'
Added package 'System.ValueTuple.4.5.0' to folder 'C:\Users\Admin\source\repos\dddemo\packages'
Added package 'System.ValueTuple.4.5.0' to 'packages.config'
Successfully installed 'System.ValueTuple 4.5.0' to dddemo
Install failed. Rolling back...
Package 'sdpeval.1.0.19114.2 : Common.Logging [3.4.1, ), FSharp.Core [4.6.2, ), Microsoft.CSharp [4.5.0, ), System.ValueTuple [4.5.0, )' does not exist in project 'dddemo'
Removed package 'System.ValueTuple.4.5.0' from 'packages.config'
Removed package 'Common.Logging.3.4.1 : Common.Logging.Core [3.4.1, )' from 'packages.config'
Removed package 'Common.Logging.Core.3.4.1 : Microsoft.CSharp [4.0.1, )' from 'packages.config'
Removed package 'Microsoft.CSharp.4.5.0' from 'packages.config'
Removed package 'FSharp.Core.4.6.2' from 'packages.config'
Package 'sdpeval.1.0.19114.2 : Common.Logging [3.4.1, ), FSharp.Core [4.6.2, ), Microsoft.CSharp [4.5.0, ), System.ValueTuple [4.5.0, )' does not exist in folder 'C:\Users\Admin\source\repos\dddemo\packages'
Removing package 'System.ValueTuple.4.5.0' from folder 'C:\Users\Admin\source\repos\dddemo\packages'
Removed package 'System.ValueTuple.4.5.0' from folder 'C:\Users\Admin\source\repos\dddemo\packages'
Removing package 'Common.Logging.3.4.1 : Common.Logging.Core [3.4.1, )' from folder 'C:\Users\Admin\source\repos\dddemo\packages'
Removed package 'Common.Logging.3.4.1 : Common.Logging.Core [3.4.1, )' from folder 'C:\Users\Admin\source\repos\dddemo\packages'
Removing package 'Common.Logging.Core.3.4.1 : Microsoft.CSharp [4.0.1, )' from folder 'C:\Users\Admin\source\repos\dddemo\packages'
Removed package 'Common.Logging.Core.3.4.1 : Microsoft.CSharp [4.0.1, )' from folder 'C:\Users\Admin\source\repos\dddemo\packages'
Removing package 'Microsoft.CSharp.4.5.0' from folder 'C:\Users\Admin\source\repos\dddemo\packages'
Removed package 'Microsoft.CSharp.4.5.0' from folder 'C:\Users\Admin\source\repos\dddemo\packages'
Removing package 'FSharp.Core.4.6.2' from folder 'C:\Users\Admin\source\repos\dddemo\packages'
Removed package 'FSharp.Core.4.6.2' from folder 'C:\Users\Admin\source\repos\dddemo\packages'
Executing nuget actions took 6.63 sec
Could not install package 'sdpeval 1.0.19114.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Time Elapsed: 00:00:08.7172216
========== Finished ==========

**Comment by trondr** [comment]
sdpeval currently only supports .NET Framework 4.7.2
